# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5645:5432
    environment:
      POSTGRES_PASSWORD: user11920
      POSTGRES_USER: shop_user
      POSTGRES_DB: shopDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080