# Generated by Django 5.0.6 on 2024-06-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactus_email_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
