# Generated by Django 5.0.6 on 2024-05-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_detail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.FloatField(),
        ),
    ]
