# Generated by Django 5.0.6 on 2024-05-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.CharField(verbose_name=50),
        ),
    ]
