# Generated by Django 5.0.6 on 2024-05-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_detail_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='discount',
            new_name='count',
        ),
    ]
