# Generated by Django 5.0.6 on 2024-05-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_discount_detail_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='count',
            new_name='discount',
        ),
    ]
