# Generated by Django 5.0.6 on 2024-05-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_count_detail_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
    ]
