# Generated by Django 5.0.6 on 2024-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.CharField(max_length=50),
        ),
    ]
