# Generated by Django 5.0.6 on 2024-05-31 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_discount_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='discount',
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='detail',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.discount'),
        ),
    ]
