# Generated by Django 5.0.6 on 2024-06-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
