# Generated by Django 5.0.6 on 2024-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_detail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='size',
        ),
        migrations.AddField(
            model_name='detail',
            name='size',
            field=models.ManyToManyField(to='products.size'),
        ),
    ]
