# Generated by Django 5.0.6 on 2024-06-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_detail_size_detail_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='size',
        ),
    ]
