# Generated by Django 5.0.6 on 2024-06-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_detail_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.size'),
        ),
    ]
