# Generated by Django 5.0.6 on 2024-06-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.color'),
        ),
    ]
